# Generated by Django 6.0.7 on 2026-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'شخصي'), ('company', 'شركة'), ('government', 'جهة حكومية')], default='individual', max_length=20),
        ),
    ]
