# Generated by Django 6.0.7 on 2026-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('link', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_en', models.CharField(blank=True, max_length=500)),
                ('value_ar', models.CharField(blank=True, max_length=500)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255)),
                ('meta_title_ar', models.CharField(blank=True, max_length=255)),
                ('meta_desc_en', models.CharField(blank=True, max_length=500)),
                ('meta_desc_ar', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
