# Generated by Django 6.0.7 on 2026-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('cities', models.JSONField(default=list)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_days_en', models.CharField(blank=True, max_length=100)),
                ('estimated_days_ar', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
