# Generated by Django 6.0.7 on 2026-08-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_desc_en', models.CharField(blank=True, max_length=500)),
                ('short_desc_ar', models.CharField(blank=True, max_length=500)),
                ('desc_en', models.TextField(blank=True)),
                ('desc_ar', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('video_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('rating_avg', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sfda_number', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('warranty_en', models.CharField(blank=True, max_length=255)),
                ('warranty_ar', models.CharField(blank=True, max_length=255)),
                ('compliance_standard', models.CharField(blank=True, max_length=255)),
                ('meta_title_en', models.CharField(blank=True, max_length=255)),
                ('meta_title_ar', models.CharField(blank=True, max_length=255)),
                ('meta_desc_en', models.CharField(blank=True, max_length=500)),
                ('meta_desc_ar', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_products', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
    ]
